# Very similar to the release build.
# Feel free to merge those into a single yaml
{
  "name": "Manual Build",
  "on": [
    "workflow_dispatch"
  ],
  "jobs": {
    "build-valetudo": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Use Node.js 16.x",
          "uses": "actions/setup-node@v1",
          "with": {
            "node-version": "16.x"
          }
        },
        {
          "name": "Install",
          "run": "npm ci"
        },
        {
          "name": "Generate OpenAPI Docs",
          "run": "npm run build_openapi_schema"
        },
        {
          "name": "Build Valetudo armv7",
          "run": "npm run build --workspace=backend"
        },
        {
          "name": "Build Valetudo armv7 lowmem",
          "run": "npm run build_armv7_lowmem --workspace=backend"
        },
        {
          "name": "Build Valetudo aarch64",
          "run": "npm run build_aarch64 --workspace=backend"
        },

        {
          "name": "Upload armv7 build",
          "uses": "actions/upload-artifact@v2",
          "with": {
            "name": "valetudo-armv7",
            "path": "./build/armv7/valetudo"
          }
        },
        {
          "name": "Upload armv7 lowmem build",
          "uses": "actions/upload-artifact@v2",
          "with": {
            "name": "valetudo-armv7-lowmem",
            "path": "./build/armv7/valetudo_lowmem"
          }
        },
        {
          "name": "Upload aarch64 build",
          "uses": "actions/upload-artifact@v2",
          "with": {
            "name": "valetudo-aarch64",
            "path": "./build/aarch64/valetudo"
          }
        }
      ]
    }
  }
}
